# Change these first
owner: phpbb # Your GitHub organization or username, where this repository lives
repo: status-site # The name of this repository

sites:
  - name: phpBB.com
    url: https://www.phpbb.com
  - name: Area51
    url: https://area51.phpbb.com
  - name: Tracker
    url: https://tracker.phpbb.com
  - name: Versioncheck
    url: https://version.phpbb.com
  - name: Blog
    url: https://blog.phpbb.com
  - name: Downloads
    url: https://download.phpbb.com
  - name: Demo
    url: http://try-phpbb.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.phpbb.com
  baseUrl: /status-site
  logoUrl: https://raw.githubusercontent.com/phpbb/phpbb/master/phpBB/styles/all/imgs/svg/phpbb_logo_large_cosmic.svg
  name: phpBB Status Site
  introTitle: Latest Updates
  introMessage: Site to announce any maintenance and the current status of phpBB Group Sites
  navbar:
    - title: Home
      href: https://www.phpbb.com/
    - title: Status
      href: /
    - title: Contact
      href: https://www.phpbb.com/about/contact/

commitMessages:
  commitAuthorName: "phpbb-user"
  commitAuthorEmail: "phpbb-user@phpbb.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
